#!/bin/bash

my_array=("value 1" "value 2" "value 3" "value 4")

echo ${my_array[0]} # Here we must use curly braces...
echo ${my_array[-1]} # Accepts negative indices...

echo ${my_array[@]} # Get all the elements of array or entire array...
echo ${#my_array[@]} # Prepend it with # to get total number of elements...